/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import org.junit.jupiter.api.Test;

;

/**
 * Model tests for AddressDetails
 */
public class AddressDetailsTest {
    private final AddressDetails model = new AddressDetails();

    /**
     * Model tests for AddressDetails
     */
    @Test
    public void testAddressDetails() {
        // TODO: test AddressDetails
    }

    /**
     * Test the property 'streetNumber'
     */
    @Test
    public void streetNumberTest() {
        // TODO: test streetNumber
    }

    /**
     * Test the property 'streetName'
     */
    @Test
    public void streetNameTest() {
        // TODO: test streetName
    }

    /**
     * Test the property 'streetType'
     */
    @Test
    public void streetTypeTest() {
        // TODO: test streetType
    }

    /**
     * Test the property 'deliveryService'
     */
    @Test
    public void deliveryServiceTest() {
        // TODO: test deliveryService
    }

    /**
     * Test the property 'buildingName'
     */
    @Test
    public void buildingNameTest() {
        // TODO: test buildingName
    }

    /**
     * Test the property 'subBuilding'
     */
    @Test
    public void subBuildingTest() {
        // TODO: test subBuilding
    }

}
