/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoicesRemind400Response
 */
public class InvoicesRemind400ResponseTest {
    private final InvoicesRemind400Response model = new InvoicesRemind400Response();

    /**
     * Model tests for InvoicesRemind400Response
     */
    @Test
    public void testInvoicesRemind400Response() {
        // TODO: test InvoicesRemind400Response
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'issues'
     */
    @Test
    public void issuesTest() {
        // TODO: test issues
    }

    /**
     * Test the property 'debugId'
     */
    @Test
    public void debugIdTest() {
        // TODO: test debugId
    }

    /**
     * Test the property 'informationLink'
     */
    @Test
    public void informationLinkTest() {
        // TODO: test informationLink
    }

}
