/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Notification
 */
public class NotificationTest {
    private final Notification model = new Notification();

    /**
     * Model tests for Notification
     */
    @Test
    public void testNotification() {
        // TODO: test Notification
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'sendToInvoicer'
     */
    @Test
    public void sendToInvoicerTest() {
        // TODO: test sendToInvoicer
    }

    /**
     * Test the property 'sendToRecipient'
     */
    @Test
    public void sendToRecipientTest() {
        // TODO: test sendToRecipient
    }

    /**
     * Test the property 'additionalRecipients'
     */
    @Test
    public void additionalRecipientsTest() {
        // TODO: test additionalRecipients
    }

}
