/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplateInfo
 */
public class TemplateInfoTest {
    private final TemplateInfo model = new TemplateInfo();

    /**
     * Model tests for TemplateInfo
     */
    @Test
    public void testTemplateInfo() {
        // TODO: test TemplateInfo
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'invoicer'
     */
    @Test
    public void invoicerTest() {
        // TODO: test invoicer
    }

    /**
     * Test the property 'primaryRecipients'
     */
    @Test
    public void primaryRecipientsTest() {
        // TODO: test primaryRecipients
    }

    /**
     * Test the property 'additionalRecipients'
     */
    @Test
    public void additionalRecipientsTest() {
        // TODO: test additionalRecipients
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property '_configuration'
     */
    @Test
    public void _configurationTest() {
        // TODO: test _configuration
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'dueAmount'
     */
    @Test
    public void dueAmountTest() {
        // TODO: test dueAmount
    }

}
