/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.api;

import io.sinistral.s1.payments.paypal.core.ApiException;
import io.sinistral.s1.payments.paypal.models.Invoices;
import io.sinistral.s1.payments.paypal.models.SearchData;
import org.junit.Ignore;
import org.junit.jupiter.api.Test;

import java.util.concurrent.CompletableFuture;

/**
 * API tests for SearchInvoicesApi
 */
@Ignore
public class SearchInvoicesApiTest {

    private final SearchInvoicesApi api = new SearchInvoicesApi();

    
    /**
     * Search for invoices
     *
     * Searches for and lists invoices that match search criteria. If you pass multiple criteria, the response lists invoices that match all criteria.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invoicesSearchInvoicesTest() throws ApiException {
        Integer page = null;
        Integer pageSize = null;
        Boolean totalRequired = null;
        SearchData searchData = null;
        CompletableFuture<Invoices> response = 
        api.invoicesSearchInvoices(page, pageSize, totalRequired, searchData);
        
        // TODO: test validations
    }
    
}
