/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;
import java.util.StringJoiner;


/**
 * The amount range.
 */
@JsonPropertyOrder({
  AmountRange.JSON_PROPERTY_LOWER_AMOUNT,
  AmountRange.JSON_PROPERTY_UPPER_AMOUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T16:02:23.639524-07:00[America/Los_Angeles]")
public class AmountRange {
  public static final String JSON_PROPERTY_LOWER_AMOUNT = "lower_amount";
  private Money lowerAmount;

  public static final String JSON_PROPERTY_UPPER_AMOUNT = "upper_amount";
  private Money upperAmount;

  public AmountRange() { 
  }

  public AmountRange lowerAmount(Money lowerAmount) {
    this.lowerAmount = lowerAmount;
    return this;
  }

   /**
   * Get lowerAmount
   * @return lowerAmount
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LOWER_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getLowerAmount() {
    return lowerAmount;
  }


  @JsonProperty(JSON_PROPERTY_LOWER_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLowerAmount(Money lowerAmount) {
    this.lowerAmount = lowerAmount;
  }


  public AmountRange upperAmount(Money upperAmount) {
    this.upperAmount = upperAmount;
    return this;
  }

   /**
   * Get upperAmount
   * @return upperAmount
  **/
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPPER_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Money getUpperAmount() {
    return upperAmount;
  }


  @JsonProperty(JSON_PROPERTY_UPPER_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpperAmount(Money upperAmount) {
    this.upperAmount = upperAmount;
  }


  /**
   * Return true if this amount_range object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AmountRange amountRange = (AmountRange) o;
    return Objects.equals(this.lowerAmount, amountRange.lowerAmount) &&
        Objects.equals(this.upperAmount, amountRange.upperAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lowerAmount, upperAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AmountRange {\n");
    sb.append("    lowerAmount: ").append(toIndentedString(lowerAmount)).append("\n");
    sb.append("    upperAmount: ").append(toIndentedString(upperAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `lower_amount` to the URL query string
    if (getLowerAmount() != null) {
      joiner.add(getLowerAmount().toUrlQueryString(prefix + "lower_amount" + suffix));
    }

    // add `upper_amount` to the URL query string
    if (getUpperAmount() != null) {
      joiner.add(getUpperAmount().toUrlQueryString(prefix + "upper_amount" + suffix));
    }

    return joiner.toString();
  }
}

