package io.sinistral.s1.payments.paypal.models;

import java.util.HashMap;
import java.util.Map;

public enum EventName {
    AUTHORIZE("authorize"),
    BILLING_PLAN_ACTIVATED("BILLING.PLAN.ACTIVATED"),
    BILLING_PLAN_CREATED("BILLING.PLAN.CREATED"),
    BILLING_PLAN_DEACTIVATED("BILLING.PLAN.DEACTIVATED"),
    BILLING_PLAN_PRICING_CHANGE_ACTIVATED("BILLING.PLAN.PRICING-CHANGE.ACTIVATED"),
    BILLING_PLAN_UPDATED("BILLING.PLAN.UPDATED"),
    BILLING_SUBSCRIPTION_ACTIVATED("BILLING.SUBSCRIPTION.ACTIVATED"),
    BILLING_SUBSCRIPTION_CANCELLED("BILLING.SUBSCRIPTION.CANCELLED"),
    BILLING_SUBSCRIPTION_CREATED("BILLING.SUBSCRIPTION.CREATED"),
    BILLING_SUBSCRIPTION_EXPIRED("BILLING.SUBSCRIPTION.EXPIRED"),
    BILLING_SUBSCRIPTION_PAYMENT_FAILED("BILLING.SUBSCRIPTION.PAYMENT.FAILED"),
    BILLING_SUBSCRIPTION_REACTIVATED("BILLING.SUBSCRIPTION.RE-ACTIVATED"),
    BILLING_SUBSCRIPTION_SUSPENDED("BILLING.SUBSCRIPTION.SUSPENDED"),
    BILLING_SUBSCRIPTION_UPDATED("BILLING.SUBSCRIPTION.UPDATED"),
    CATALOG_PRODUCT_CREATED("CATALOG.PRODUCT.CREATED"),
    CATALOG_PRODUCT_UPDATED("CATALOG.PRODUCT.UPDATED"),
    CHECKOUT_CHECKOUT_BUYER_APPROVED("CHECKOUT.CHECKOUT.BUYER-APPROVED"),
    CHECKOUT_ORDER_APPROVED("CHECKOUT.ORDER.APPROVED"),
    CHECKOUT_ORDER_COMPLETED("CHECKOUT.ORDER.COMPLETED"),
    CHECKOUT_ORDER_PROCESSED("CHECKOUT.ORDER.PROCESSED"),
    CHECKOUT_PAYMENT_APPROVAL_REVERSED("CHECKOUT.PAYMENT-APPROVAL.REVERSED"),
    COMPLETED("completed"),
    CUSTOMER_ACCOUNT_LIMITATION_ADDED("CUSTOMER.ACCOUNT-LIMITATION.ADDED"),
    CUSTOMER_ACCOUNT_LIMITATION_ESCALATED("CUSTOMER.ACCOUNT-LIMITATION.ESCALATED"),
    CUSTOMER_ACCOUNT_LIMITATION_LIFTED("CUSTOMER.ACCOUNT-LIMITATION.LIFTED"),
    CUSTOMER_ACCOUNT_LIMITATION_UPDATED("CUSTOMER.ACCOUNT-LIMITATION.UPDATED"),
    CUSTOMER_DISPUTE_CREATED("CUSTOMER.DISPUTE.CREATED"),
    CUSTOMER_DISPUTE_RESOLVED("CUSTOMER.DISPUTE.RESOLVED"),
    CUSTOMER_DISPUTE_UPDATED("CUSTOMER.DISPUTE.UPDATED"),
    CUSTOMER_MERCHANT_INTEGRATION_CAPABILITY_UPDATED("CUSTOMER.MERCHANT-INTEGRATION.CAPABILITY-UPDATED"),
    CUSTOMER_MERCHANT_INTEGRATION_PRODUCT_SUBSCRIPTION_UPDATED("CUSTOMER.MERCHANT-INTEGRATION.PRODUCT-SUBSCRIPTION-UPDATED"),
    CUSTOMER_MERCHANT_INTEGRATION_SELLER_ALREADY_INTEGRATED("CUSTOMER.MERCHANT-INTEGRATION.SELLER-ALREADY-INTEGRATED"),
    CUSTOMER_MERCHANT_INTEGRATION_SELLER_CONSENT_GRANTED("CUSTOMER.MERCHANT-INTEGRATION.SELLER-CONSENT-GRANTED"),
    CUSTOMER_MERCHANT_INTEGRATION_SELLER_EMAIL_CONFIRMED("CUSTOMER.MERCHANT-INTEGRATION.SELLER-EMAIL-CONFIRMED"),
    CUSTOMER_MERCHANT_INTEGRATION_SELLER_ONBOARDING_INITIATED("CUSTOMER.MERCHANT-INTEGRATION.SELLER-ONBOARDING-INITIATED"),
    DECLINED("declined"),
    IDENTITY_AUTHORIZATION_CONSENT_REVOKED("IDENTITY.AUTHORIZATION-CONSENT.REVOKED"),
    INTENT("intent"),
    INVOICING_INVOICE_CANCELLED("INVOICING.INVOICE.CANCELLED"),
    INVOICING_INVOICE_CREATED("INVOICING.INVOICE.CREATED"),
    INVOICING_INVOICE_PAID("INVOICING.INVOICE.PAID"),
    INVOICING_INVOICE_REFUNDED("INVOICING.INVOICE.REFUNDED"),
    INVOICING_INVOICE_SCHEDULED("INVOICING.INVOICE.SCHEDULED"),
    INVOICING_INVOICE_UPDATED("INVOICING.INVOICE.UPDATED"),
    MERCHANT_MANAGED_ACCOUNT_ACCOUNT_CREATED("MERCHANT.MANAGED-ACCOUNT.ACCOUNT-CREATED"),
    MERCHANT_MANAGED_ACCOUNT_ACCOUNT_STATUS_CHANGED("MERCHANT.MANAGED-ACCOUNT.ACCOUNT-STATUS-CHANGED"),
    MERCHANT_MANAGED_ACCOUNT_ACCOUNT_UPDATED("MERCHANT.MANAGED-ACCOUNT.ACCOUNT-UPDATED"),
    MERCHANT_MANAGED_ACCOUNT_CREATION_FAILED("MERCHANT.MANAGED-ACCOUNT.CREATION-FAILED"),
    MERCHANT_MANAGED_ACCOUNT_NEGATIVE_BALANCE_DEBIT_INITIATED("MERCHANT.MANAGED-ACCOUNT.NEGATIVE-BALANCE-DEBIT-INITIATED"),
    MERCHANT_MANAGED_ACCOUNT_NEGATIVE_BALANCE_NOTIFIED("MERCHANT.MANAGED-ACCOUNT.NEGATIVE-BALANCE-NOTIFIED"),
    MERCHANT_MANAGED_ACCOUNT_RISK_ASSESSED("MERCHANT.MANAGED-ACCOUNT.RISK-ASSESSED"),
    MERCHANT_ONBOARDING_COMPLETED("MERCHANT.ONBOARDING.COMPLETED"),
    MERCHANT_PARTNER_CONSENT_REVOKED("MERCHANT.PARTNER-CONSENT.REVOKED"),
    PAYMENTS_PAYMENT_CREATED("PAYMENTS.PAYMENT.CREATED"),
    PAYMENT_AUTHORIZATION_CREATED("PAYMENT.AUTHORIZATION.CREATED"),
    PAYMENT_AUTHORIZATION_VOIDED("PAYMENT.AUTHORIZATION.VOIDED"),
    PAYMENT_CAPTURE_COMPLETED("PAYMENT.CAPTURE.COMPLETED"),
    PAYMENT_CAPTURE_DECLINED("PAYMENT.CAPTURE.DECLINED"),
    PAYMENT_CAPTURE_DENIED("PAYMENT.CAPTURE.DENIED"),
    PAYMENT_CAPTURE_PENDING("PAYMENT.CAPTURE.PENDING"),
    PAYMENT_CAPTURE_REFUNDED("PAYMENT.CAPTURE.REFUNDED"),
    PAYMENT_CAPTURE_REVERSED("PAYMENT.CAPTURE.REVERSED"),
    PAYMENT_ORDER_CANCELLED("PAYMENT.ORDER.CANCELLED"),
    PAYMENT_ORDER_CREATED("PAYMENT.ORDER.CREATED"),
    PAYMENT_PAYOUTSBATCH_DENIED("PAYMENT.PAYOUTSBATCH.DENIED"),
    PAYMENT_PAYOUTSBATCH_PROCESSING("PAYMENT.PAYOUTSBATCH.PROCESSING"),
    PAYMENT_PAYOUTSBATCH_SUCCESS("PAYMENT.PAYOUTSBATCH.SUCCESS"),
    PAYMENT_PAYOUTS_ITEM_BLOCKED("PAYMENT.PAYOUTS-ITEM.BLOCKED"),
    PAYMENT_PAYOUTS_ITEM_CANCELED("PAYMENT.PAYOUTS-ITEM.CANCELED"),
    PAYMENT_PAYOUTS_ITEM_DENIED("PAYMENT.PAYOUTS-ITEM.DENIED"),
    PAYMENT_PAYOUTS_ITEM_FAILED("PAYMENT.PAYOUTS-ITEM.FAILED"),
    PAYMENT_PAYOUTS_ITEM_HELD("PAYMENT.PAYOUTS-ITEM.HELD"),
    PAYMENT_PAYOUTS_ITEM_REFUNDED("PAYMENT.PAYOUTS-ITEM.REFUNDED"),
    PAYMENT_PAYOUTS_ITEM_RETURNED("PAYMENT.PAYOUTS-ITEM.RETURNED"),
    PAYMENT_PAYOUTS_ITEM_SUCCEEDED("PAYMENT.PAYOUTS-ITEM.SUCCEEDED"),
    PAYMENT_PAYOUTS_ITEM_UNCLAIMED("PAYMENT.PAYOUTS-ITEM.UNCLAIMED"),
    PAYMENT_REFERENCED_PAYOUT_ITEM_COMPLETE("PAYMENT.REFERENCED-PAYOUT-ITEM.COMPLETE"),
    PAYMENT_REFERENCED_PAYOUT_ITEM_COMPLETED("PAYMENT.REFERENCED-PAYOUT-ITEM.COMPLETED"),
    PAYMENT_REFERENCED_PAYOUT_ITEM_FAILED("PAYMENT.REFERENCED-PAYOUT-ITEM.FAILED"),
    PAYMENT_SALE_COMPLETED("PAYMENT.SALE.COMPLETED"),
    PAYMENT_SALE_DENIED("PAYMENT.SALE.DENIED"),
    PAYMENT_SALE_PENDING("PAYMENT.SALE.PENDING"),
    PAYMENT_SALE_REFUNDED("PAYMENT.SALE.REFUNDED"),
    PAYMENT_SALE_REVERSED("PAYMENT.SALE.REVERSED"),
    PAYOUTSBATCH("PAYOUTSBATCH"),
    PENDING("pending"),
    PPCP("PPCP"),
    REFUNDED("refunded"),
    RISK_DISPUTE_CREATED("RISK.DISPUTE.CREATED"),
    STATUS("status"),
    VAULT_CREDIT_CARD_CREATED("VAULT.CREDIT-CARD.CREATED"),
    VAULT_CREDIT_CARD_DELETED("VAULT.CREDIT-CARD.DELETED"),
    VAULT_CREDIT_CARD_UPDATED("VAULT.CREDIT-CARD.UPDATED"),
    VOIDED("voided");

    private static final Map<String, EventName> BY_TITLE = new HashMap<>();

    static {
        for (EventName eventName : values()) {
            BY_TITLE.put(eventName.title, eventName);
        }
    }

    private final String title;

    EventName(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public static EventName valueOfTitle(String title) {
        return BY_TITLE.get(title);
    }
}
