/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;
import java.util.StringJoiner;


/**
 * The billing and shipping information. Includes name, email, address, phone, and language.
 */
@JsonPropertyOrder({
  RecipientInfo.JSON_PROPERTY_BILLING_INFO,
  RecipientInfo.JSON_PROPERTY_SHIPPING_INFO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T16:02:23.639524-07:00[America/Los_Angeles]")
public class RecipientInfo {
  public static final String JSON_PROPERTY_BILLING_INFO = "billing_info";
  private BillingInfo billingInfo;

  public static final String JSON_PROPERTY_SHIPPING_INFO = "shipping_info";
  private ContactNameAddress shippingInfo;

  public RecipientInfo() { 
  }

  public RecipientInfo billingInfo(BillingInfo billingInfo) {
    this.billingInfo = billingInfo;
    return this;
  }

   /**
   * Get billingInfo
   * @return billingInfo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BillingInfo getBillingInfo() {
    return billingInfo;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingInfo(BillingInfo billingInfo) {
    this.billingInfo = billingInfo;
  }


  public RecipientInfo shippingInfo(ContactNameAddress shippingInfo) {
    this.shippingInfo = shippingInfo;
    return this;
  }

   /**
   * Get shippingInfo
   * @return shippingInfo
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ContactNameAddress getShippingInfo() {
    return shippingInfo;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingInfo(ContactNameAddress shippingInfo) {
    this.shippingInfo = shippingInfo;
  }


  /**
   * Return true if this recipient_info object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientInfo recipientInfo = (RecipientInfo) o;
    return Objects.equals(this.billingInfo, recipientInfo.billingInfo) &&
        Objects.equals(this.shippingInfo, recipientInfo.shippingInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billingInfo, shippingInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientInfo {\n");
    sb.append("    billingInfo: ").append(toIndentedString(billingInfo)).append("\n");
    sb.append("    shippingInfo: ").append(toIndentedString(shippingInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `billing_info` to the URL query string
    if (getBillingInfo() != null) {
      joiner.add(getBillingInfo().toUrlQueryString(prefix + "billing_info" + suffix));
    }

    // add `shipping_info` to the URL query string
    if (getShippingInfo() != null) {
      joiner.add(getShippingInfo().toUrlQueryString(prefix + "shipping_info" + suffix));
    }

    return joiner.toString();
  }
}

