/*
 * Invoices
 * Use the Invoicing API to create, send, and manage invoices. You can also use the API or webhooks to track invoice payments. When you send an invoice to a customer, the invoice moves from draft to payable state. PayPal then emails the customer a link to the invoice on the PayPal website. Customers with a PayPal account can log in and pay the invoice with PayPal. Alternatively, customers can pay as a guest with a debit card or credit card. For more information, see the <a href=\"/docs/invoicing/\">Invoicing Overview</a> and the <a href=\"/docs/invoicing/basic-integration/\">Invoicing Integration Guide</a>.
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.sinistral.s1.payments.paypal.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Objects;
import java.util.StringJoiner;


/**
 * The template subtotal setting. Includes the field name and display preference.
 */
@JsonPropertyOrder({
  TemplateSubtotalSetting.JSON_PROPERTY_FIELD_NAME,
  TemplateSubtotalSetting.JSON_PROPERTY_DISPLAY_PREFERENCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T16:02:23.639524-07:00[America/Los_Angeles]")
public class TemplateSubtotalSetting {
  public static final String JSON_PROPERTY_FIELD_NAME = "field_name";
  private TemplateSubtotalField fieldName;

  public static final String JSON_PROPERTY_DISPLAY_PREFERENCE = "display_preference";
  private TemplateDisplayPreference displayPreference;

  public TemplateSubtotalSetting() { 
  }

  public TemplateSubtotalSetting fieldName(TemplateSubtotalField fieldName) {
    this.fieldName = fieldName;
    return this;
  }

   /**
   * Get fieldName
   * @return fieldName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TemplateSubtotalField getFieldName() {
    return fieldName;
  }


  @JsonProperty(JSON_PROPERTY_FIELD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFieldName(TemplateSubtotalField fieldName) {
    this.fieldName = fieldName;
  }


  public TemplateSubtotalSetting displayPreference(TemplateDisplayPreference displayPreference) {
    this.displayPreference = displayPreference;
    return this;
  }

   /**
   * Get displayPreference
   * @return displayPreference
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISPLAY_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TemplateDisplayPreference getDisplayPreference() {
    return displayPreference;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayPreference(TemplateDisplayPreference displayPreference) {
    this.displayPreference = displayPreference;
  }


  /**
   * Return true if this template_subtotal_setting object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplateSubtotalSetting templateSubtotalSetting = (TemplateSubtotalSetting) o;
    return Objects.equals(this.fieldName, templateSubtotalSetting.fieldName) &&
        Objects.equals(this.displayPreference, templateSubtotalSetting.displayPreference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldName, displayPreference);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplateSubtotalSetting {\n");
    sb.append("    fieldName: ").append(toIndentedString(fieldName)).append("\n");
    sb.append("    displayPreference: ").append(toIndentedString(displayPreference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `field_name` to the URL query string
    if (getFieldName() != null) {
      joiner.add(String.format("%sfield_name%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFieldName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `display_preference` to the URL query string
    if (getDisplayPreference() != null) {
      joiner.add(getDisplayPreference().toUrlQueryString(prefix + "display_preference" + suffix));
    }

    return joiner.toString();
  }
}

